# Makefile for ep_dispatch_bench_mpi_cpu.c
# Build inside the uenv with: make -f Makefile.ep_mpi_cpu

MPICC ?= cc
CFLAGS = -O2 -std=gnu11 -Wall

ep_dispatch_bench_mpi_cpu: ep_dispatch_bench_mpi_cpu.c
	$(MPICC) $(CFLAGS) -o $@ $<

ep_dispatch_bench_mpi_cpu_p2p: ep_dispatch_bench_mpi_cpu_p2p.c
	$(MPICC) $(CFLAGS) -o $@ $<

clean:
	rm -f ep_dispatch_bench_mpi_cpu ep_dispatch_bench_mpi_cpu_p2p

.PHONY: clean
